on: [ pull_request ]

jobs:
  automerge:
    if: github.event.pull_request.user.login == 'marten-seemann'
    runs-on: ubuntu-latest
    steps:
    - name: Merge PR
      uses: pascalgn/automerge-action@v0.13.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
        MERGE_RETRY_SLEEP: 15000 # 15s
        MERGE_RETRIES: 60 # only merge if test complete within 60 * 15s = 15 min
