on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hallo"
      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: getmergedpr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.getmergedpr.outputs.title }}
        if: steps.getmergedpr.outputs.title != ''
      - run: echo ${{ steps.getmergedpr.outputs.body }}
      - run: echo ${{ steps.getmergedpr.outputs.number }}
      - run: echo ${{ steps.getmergedpr.outputs.labels }}
