on:
  push:
    paths:
      - 'version.json'
  pull_request:
    paths:
      - 'version.json'

jobs:
  releaser:
    # run if:
    # 1. This is a PR targeting the default branch, OR
    # 2. This is a commit on the default branch.
    if: (${{ github.event_name }} == "pull_request" && ${{ github.base_ref }} == ${{ github.event.repository.default_branch }}) || (${{ github.event_name }} == "push" && ${{ github.head_ref }} == ${{ github.event.repository.default_branch }})
    runs-on: ubuntu-latest
    env:
      VERSION: ""
    steps:
      - name: debug GITHUB_EVENT_PATH
        run: cat "$GITHUB_EVENT_PATH" | jq -M .
      - name: debug GITHUB_REF
        run: cat "$GITHUB_REF" | jq -M .
      - uses: actions/checkout@v2
      - name: Determine version
        run: |
          v=$(jq -r .version version.json)
          echo $v
          echo "VERSION=$v" >> $GITHUB_ENV
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.event.repository.default_branch }}
      - name: Create release
        if: ${{ github.event_name == 'push' && github.head_ref == github.event.repository.default_branch }}
        run: |
          git tag ${{ env.VERSION }}
          git push --tags 
