on:
  push:
    paths:
      - 'version.json'
  pull_request:
    paths:
      - 'version.json'

jobs:
  releaser:
    if: ${{ github.event_name }} == "pull_request" && ${{ github.base_ref }} == ${{ github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    env:
      VERSION: ""
    steps:
      - name: debug GITHUB_EVENT_PATH
        run: cat "$GITHUB_EVENT_PATH" | jq -M .
      - name: debug GITHUB_REF
        run: cat "$GITHUB_REF" | jq -M .
      - uses: actions/checkout@v2
      - name: Create release
        run: |
          v=$(jq -r .version version.json)
          echo $v
          echo "VERSION=$v" >> $GITHUB_ENV
      - name: Create release
        if: ${{ github.event_name }} == "push"
        run: |
          git tag ${{ env.VERSION }}
          git push --tags 
