on:
  push:
    tags:
      - v*

jobs:
  unit:
    runs-on: ubuntu-latest
    name: All
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: "1.16.x"
      - name: Install gorelease
        run: go install golang.org/x/exp/cmd/gorelease@v0.0.0-20210729172720-737cce5152fc
      - name: Debug
        run: cat "$GITHUB_EVENT_PATH" | jq -M .
      - name: Find tag
        run: |
          ref="${{ github.event.ref }}"
          IFS='/'; split=($ref); unset IFS;
          tag=${split[2]}
          echo "Tag: $tag"
          git tag -d "$tag"
          suggested=$(gorelease | grep Suggested | sed "s/Suggested version: //")
