on:
  push:
    tags:

jobs:
  unit:
    runs-on: ubuntu-latest
    name: All
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: "1.16.x"
      - name: Install gorelease
        run: go install golang.org/x/exp/cmd/gorelease@v0.0.0-20210729172720-737cce5152fc
      - name: Debug
        run: cat "$GITHUB_EVENT_PATH" | jq -M .
      - run: |
          ref="${{ github.event.ref }}"
          echo $ref
          IFS='/'; split=($IN); unset IFS;
          echo ${split[2]}
